<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Check Eligibility</name>
   <tag></tag>
   <elementGuidId>b3130657-992f-4037-aeac-676bd6c88e76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-lg.btn-primary.h-60px.fs-7.mbutton.w-100.fw-bolder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Check Eligibility&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>668dc68a-2031-4f6b-a1d0-d9d261c8c4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c54c8ca8-0b54-4760-8053-9f7a5a685cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-primary h-60px fs-7 mbutton w-100 fw-bolder</value>
      <webElementGuid>85f26bdb-5944-466b-9446-2da43c805544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Check Eligibility </value>
      <webElementGuid>7fc8a11c-8571-4a25-a034-25368b83c0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_stepper_example_vertical&quot;)/div[@class=&quot;flex-row-fluid card w-100 shadow-sm p-20 min-h-500px&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[1]/form[@class=&quot;w-xs-100 w-xl-75 ng-star-inserted ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mt-5 d-flex align-items-center&quot;]/button[@class=&quot;btn btn-lg btn-primary h-60px fs-7 mbutton w-100 fw-bolder&quot;]</value>
      <webElementGuid>a5d7973e-b489-4a86-8470-ad33953118f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>6a718d21-a1e0-479a-8b73-39c36e015001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Check Eligibility ' or . = 'Check Eligibility ')]</value>
      <webElementGuid>9adacc7d-502f-4e2f-bf36-831615180de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff Number'])[1]/following::button[1]</value>
      <webElementGuid>4ef3f37a-800c-42d4-af82-5e7653ea5d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='World Health Organization'])[1]/following::button[1]</value>
      <webElementGuid>369297f4-102f-4a5a-84e9-6bcb25e94018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TERMS AND CONDITIONS'])[1]/preceding::button[1]</value>
      <webElementGuid>ce83f036-92e9-4ea0-917a-1c2e1f4fc49b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The client acknowledges that this service is voluntarily undertaken by the client.'])[1]/preceding::button[1]</value>
      <webElementGuid>feaac23c-75f0-4c13-8307-dab2baed56d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Check Eligibility']/parent::*</value>
      <webElementGuid>05bd0f2e-3a38-44bf-adef-a213a9d2eb88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_stepper_example_vertical']/div[2]/div/div[2]/div/div/form/div/div[3]/button</value>
      <webElementGuid>b048cfa1-5803-4f1f-b7bd-bc2319d4afbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/button</value>
      <webElementGuid>8a129356-9b92-41cd-b60c-f872bfa93037</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
