<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Dismiss</name>
   <tag></tag>
   <elementGuidId>0ec8ca58-0f32-4910-b3fa-57d6c1ae01a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='contact_modal_close']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.card-footer > #contact_modal_close</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'contact_modal_close' and (text() = 'Dismiss ' or . = 'Dismiss ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Dismiss&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e21ad8b-cd75-45b3-9749-1dd30a0ae2fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contact_modal_close</value>
      <webElementGuid>b30d829d-f17d-4ea5-a6f6-1217e2c59985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kt-drawer-dismiss</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>05a692a3-777b-44cd-80c1-6d8ab1b595d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger fs-7</value>
      <webElementGuid>0631db80-a625-4e42-b543-5f6aae33319a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dismiss </value>
      <webElementGuid>60c0b191-a519-4aaf-b6fc-5e23caa098dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact_modal&quot;)/div[@class=&quot;card rounded-0 w-100&quot;]/div[@class=&quot;card-footer&quot;]/button[@id=&quot;contact_modal_close&quot;]</value>
      <webElementGuid>1c24d349-6752-46c6-9828-df71e9419d67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='contact_modal_close']</value>
      <webElementGuid>ba851863-b2ab-4647-9c91-947818dfbeef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'contact_modal_close' and (text() = 'Dismiss ' or . = 'Dismiss ')]</value>
      <webElementGuid>8c0de2c5-4a53-4183-bbc5-5f7144562640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Dependants'])[1]/following::button[1]</value>
      <webElementGuid>99eb3601-d3e7-433d-b7b0-1e1ebec5c08e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/following::button[2]</value>
      <webElementGuid>f89d2dc6-2d61-45b9-99c9-40b5031fed0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Account'])[1]/preceding::button[1]</value>
      <webElementGuid>ce45f22b-901f-4760-a5ca-69e7363eacc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Profile is Incomplete'])[1]/preceding::button[2]</value>
      <webElementGuid>19bec656-d2cf-4c2d-bb46-84c9b2fbc5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dismiss']/parent::*</value>
      <webElementGuid>7f12f019-fd16-4441-923f-d70e740eb786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact_modal']/div/div[3]/button</value>
      <webElementGuid>b37707fe-718e-4d77-a6e8-9a13c4e53689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>e11b3d78-b928-4b86-b67d-2a3b8bed6619</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
