<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Bank2</name>
   <tag></tag>
   <elementGuidId>3721b638-41fe-4fe7-ac1b-2beebd5b0ddf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type = 'submit'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bank_modal_button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'bank_modal_button' and (text() = ' Add Bank' or . = ' Add Bank')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#bank_modal_button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2b1a00ba-5b3e-4583-a863-131920433d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bank_modal_button</value>
      <webElementGuid>2d2f05b9-6e20-480c-8069-a39dd6336c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary h-60px fs-7</value>
      <webElementGuid>324ab555-60be-4719-8f3b-8eb611b035ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add Bank</value>
      <webElementGuid>6711f195-d3f1-4b1a-9244-ea2c731d9622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bank_modal_button&quot;)</value>
      <webElementGuid>4efc1c17-1c79-4fca-867f-379ce2d6cb5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='bank_modal_button']</value>
      <webElementGuid>db96c07a-6bc0-477c-9871-a5deff890e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'bank_modal_button' and (text() = ' Add Bank' or . = ' Add Bank')]</value>
      <webElementGuid>1ed09839-b163-4893-9ab4-f35615c52193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valid To'])[1]/following::button[1]</value>
      <webElementGuid>05f6544c-3845-45ea-bf03-8b158ad1994d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valid From'])[1]/following::button[1]</value>
      <webElementGuid>67f09637-91de-4980-8567-51c70823e4cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Bank'])[1]/preceding::button[1]</value>
      <webElementGuid>7c04457b-5af9-4ec4-95df-610817cc65fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Number'])[2]/preceding::button[1]</value>
      <webElementGuid>376ee304-3545-4559-9f42-d7c688f2fdfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Bank']/parent::*</value>
      <webElementGuid>42839f4b-51bd-40a5-a225-ee0890477225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content']/div/div/div/button</value>
      <webElementGuid>e87ab681-84c7-4ce4-9345-53da0dbafd0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/button</value>
      <webElementGuid>b1cfd722-bacb-4ce7-86e0-79be71f299d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
