<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_relationship</name>
   <tag></tag>
   <elementGuidId>4f18dcf0-0400-419a-a174-ee1648c97243</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//span[text()='Relationship']//following::div[@aria-haspopup='listbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.//span[text()='Relationship']//following::div[@aria-haspopup='listbox']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
