<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Home_logo-default h-25px h-lg-30px</name>
   <tag></tag>
   <elementGuidId>55b8d148-94fa-4a9d-9dbe-1f95a34962a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt = 'Logo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.logo-default.h-25px.h-lg-30px</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Logo&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>402a81ab-0099-4843-86a4-06146bec2992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo</value>
      <webElementGuid>e0b2f657-3aca-4829-8d92-0f91f7b1d8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/img/logo_white.png</value>
      <webElementGuid>2852dcad-9b4a-49ad-abb6-80020277c802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo-default h-25px h-lg-30px</value>
      <webElementGuid>b1d54ac3-1f7b-4559-a0b9-389898c0cc23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)/div[@class=&quot;bgi-no-repeat bgi-size-contain bgi-position-x-center bgi-position-y-bottom landing-dark-bg&quot;]/app-header[1]/div[@class=&quot;landing-header&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;d-flex align-items-center justify-content-between&quot;]/div[@class=&quot;d-flex align-items-center flex-equal&quot;]/a[1]/img[@class=&quot;logo-default h-25px h-lg-30px&quot;]</value>
      <webElementGuid>1d94bb64-5820-4249-b350-0d747ec3e747</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Logo']</value>
      <webElementGuid>bacd722c-8279-4d0e-b103-7660d560af26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home']/div/app-header/div/div/div/div/a/img</value>
      <webElementGuid>eeb6d4e4-7746-469d-9599-b8bf77b35612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo']</value>
      <webElementGuid>aec5355f-5b12-403e-acd2-f5a3e830ae95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>2b294fdd-ba4a-4bfb-8c8d-1fe732b4fff2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
