<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amount_form-control _h60 fs-7 ng-unto_7828d8</name>
   <tag></tag>
   <elementGuidId>68287aaf-dd0a-43bc-a4b3-05fb2d2ae049</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control._h60.fs-7.ng-untouched.ng-dirty.ng-invalid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Amount to contribute&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4114862f-356e-406f-9715-a7bab31b59e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4515f430-dfa6-498f-8005-fde2312b0f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>10000</value>
      <webElementGuid>d34a100b-043c-47da-908e-86967ddce06e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>5000</value>
      <webElementGuid>6aebbba8-884b-4ffa-98ef-d728bb986529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>amount</value>
      <webElementGuid>58c4ee36-be33-48e7-955c-f800c6166476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Amount to contribute</value>
      <webElementGuid>18706035-63b6-4eb9-946d-0e25ad83fab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control _h60 fs-7 ng-untouched ng-dirty ng-invalid</value>
      <webElementGuid>22036b01-dacd-40f5-86c3-19bd9af90979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_drawer_example_dismiss&quot;)/div[@class=&quot;card rounded-0 w-100&quot;]/div[@class=&quot;card-body hover-scroll-overlay-y&quot;]/div[@class=&quot;card card-custom gutter-b _p50&quot;]/form[@class=&quot;form ng-dirty ng-touched ng-invalid&quot;]/div[@class=&quot;row col-xl-12&quot;]/div[@class=&quot;col-sm-12 col-xl-5&quot;]/div[@class=&quot;form-group&quot;]/div[2]/div[@class=&quot;fv-row mb-7&quot;]/input[@class=&quot;form-control _h60 fs-7 ng-untouched ng-dirty ng-invalid&quot;]</value>
      <webElementGuid>d718ccbb-8ecd-48e0-8955-9707a9d1f51a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='number']</value>
      <webElementGuid>96652fad-f088-416f-9d81-8f1c2a62b3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Amount to contribute']</value>
      <webElementGuid>09d0b933-5927-43e6-ae37-1de99b8b9b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_drawer_example_dismiss']/div/div[2]/div/form/div/div/div/div[2]/div/input</value>
      <webElementGuid>cacbe319-ac6a-4c4e-8aef-a76eac38b391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>c9bc4269-39ef-4e30-8aa7-8c5e2678330a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
