<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter the verification code here_form_669eb9</name>
   <tag></tag>
   <elementGuidId>af68ede4-93cb-4cc1-9f90-17d6f4e8e120</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'tel' and @placeholder = 'Enter code here']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.text-center._h60._ttu.text-gray-700.fs-6._fpoppins.ng-tns-c83-0.ng-untouched.ng-invalid.ng-dirty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter code here&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a636cd6-f889-4368-b056-de76b682327f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>otp</value>
      <webElementGuid>93981e85-c108-4516-9ce0-289ead2e356a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>0446bf22-9d4d-4890-9460-98ec5d4cf9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>397505d8-5552-4111-ae6c-061190eebd90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>24185c12-97c6-4ee2-8ed5-c58ae8e2232d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter code here</value>
      <webElementGuid>5b933f3b-b81f-48ec-87c0-c734ef56d2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4a6ab756-ef81-46d3-9f48-cc55490b9ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-center _h60 _ttu text-gray-700 fs-6 _fpoppins ng-tns-c83-0 ng-untouched ng-invalid ng-dirty</value>
      <webElementGuid>fee8ef70-a840-43ea-ba6d-e28dff4d2cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;header-fixed header-tablet-and-mobile-fixed aside-fixed aside-secondary-disabled&quot;]/app-root[1]/app-login[@class=&quot;ng-tns-c83-0 ng-star-inserted&quot;]/div[@class=&quot;d-flex flex-column flex-root ng-tns-c83-0&quot;]/div[@class=&quot;d-flex flex-column flex-lg-row flex-column-fluid stepper stepper-pills stepper-column ng-tns-c83-0&quot;]/div[@class=&quot;d-flex flex-column flex-lg-row-fluid py-10 bg-dark h-200vh ng-tns-c83-0&quot;]/div[@class=&quot;d-flex flex-center flex-column flex-column-fluid ng-tns-c83-0&quot;]/div[@class=&quot;row rounded align-items-center flex-center mt-10 ng-tns-c83-0 ng-star-inserted&quot;]/div[@class=&quot;col-lg-6 w-lg-500px col-md-6 _login-card ng-tns-c83-0&quot;]/div[@class=&quot;card-bordered shadow card w-100 h-500px ng-tns-c83-0&quot;]/div[@class=&quot;w-100 mt-10 options-head ng-tns-c83-0&quot;]/div[@class=&quot;w-100 px-10 ng-tns-c83-0 ng-star-inserted&quot;]/form[@class=&quot;form w-100 mb-10 px-15 ng-tns-c83-0 ng-untouched ng-invalid ng-dirty&quot;]/div[@class=&quot;mb-3 ng-tns-c83-0&quot;]/div[@class=&quot;ng-tns-c83-0&quot;]/div[@class=&quot;fv-row mb-5 mt-5 ng-tns-c83-0&quot;]/input[@class=&quot;form-control text-center _h60 _ttu text-gray-700 fs-6 _fpoppins ng-tns-c83-0 ng-untouched ng-invalid ng-dirty&quot;]</value>
      <webElementGuid>625d937e-0676-44f9-9a1c-09efe794827e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @placeholder = 'Enter code here']</value>
      <webElementGuid>bacc671e-d083-498a-8943-6dfed98078db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='tel']</value>
      <webElementGuid>2c65e9c2-04ab-4a65-b27f-79114cbcc349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8f5c3857-b9e1-4b1a-bf5a-0f5617962a3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
