<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Staff Number_form-control text-upperc_36d491</name>
   <tag></tag>
   <elementGuidId>65e4ae83-af15-4e16-aecc-dcf498e8ccb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.text-uppercase.h-60px.text-center.text-gray-700.fs-7._fpoppins.ng-untouched.ng-pristine.ng-invalid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot; Enter Supplier Number &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b7e85ce-a446-4e3e-9053-3a7cf7f428ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>54b54fef-118b-4662-b3a8-389993a0a2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>supplier_number</value>
      <webElementGuid>64a95e73-13b2-4e96-b491-f3882d0be36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>73a03810-eb40-4ae5-82c3-8f12ecae7d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>c7f45071-0c5e-42b6-b912-87a9ec413120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value> Enter Supplier Number </value>
      <webElementGuid>ca22abc0-1350-40f3-8b80-87cadb3bdd0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0b056a66-086d-4fc4-b6f7-481c5bb64eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ms-editor</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>500283c8-823d-45cc-b473-57050fc12bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-uppercase h-60px text-center text-gray-700 fs-7 _fpoppins ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>2a55afbd-be6d-4794-b683-1959b62124bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_stepper_example_vertical&quot;)/div[@class=&quot;flex-row-fluid card w-100 shadow-sm p-20 min-h-500px&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[1]/form[@class=&quot;w-xs-100 w-xl-75 ng-invalid ng-star-inserted ng-touched ng-dirty&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mb-5 mt-5 fv-row fv-plugins-icon-container&quot;]/input[@class=&quot;form-control text-uppercase h-60px text-center text-gray-700 fs-7 _fpoppins ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>49a5b8c7-7cda-40a7-a3fe-79a4e6ec7715</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>ac13745d-cf8e-4795-a751-bc8058f2ebb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = ' Enter Supplier Number ']</value>
      <webElementGuid>daa65d6c-ebbb-436d-bb71-208a58d46931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_stepper_example_vertical']/div[2]/div/div[2]/div/div/form/div/div[2]/input</value>
      <webElementGuid>0942bc69-8965-4542-b6c5-493adf18ad2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>824060db-130e-43fb-bf4d-d21646ca4a88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
