<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter the verification code here_form_196606</name>
   <tag></tag>
   <elementGuidId>4535dcb6-9d7d-43af-b55f-5a1ec2651a1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'tel' and @placeholder = 'Enter code here']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.text-center._h60._ttu.text-gray-700.fs-6._fpoppins.ng-tns-c82-0.ng-untouched.ng-invalid.ng-dirty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter code here&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0fb361f6-e659-471f-9fd0-530ca9f05537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>otp</value>
      <webElementGuid>9167f93d-0f74-4aa4-adab-6ebcccf78e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>98bb3eb8-a2fd-4701-b29b-978fd1d96edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>8ba80ed2-ff8d-4a31-bb0b-2f1878c6778e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>7e281d8d-b203-409d-bc24-78445f5c2309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter code here</value>
      <webElementGuid>2d35ea7a-ef99-46cf-856d-907aaf74c147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bfbcbab0-5be5-480e-9b78-dcad2a322eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-center _h60 _ttu text-gray-700 fs-6 _fpoppins ng-tns-c82-0 ng-untouched ng-invalid ng-dirty</value>
      <webElementGuid>07fae87c-ff48-41bf-90f3-8976b24c5248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;header-fixed header-tablet-and-mobile-fixed aside-fixed aside-secondary-disabled&quot;]/app-root[1]/app-login[@class=&quot;ng-tns-c82-0 ng-star-inserted&quot;]/div[@class=&quot;d-flex flex-column flex-root ng-tns-c82-0&quot;]/div[@class=&quot;d-flex flex-column flex-lg-row flex-column-fluid stepper stepper-pills stepper-column ng-tns-c82-0&quot;]/div[@class=&quot;d-flex flex-column flex-lg-row-fluid py-10 bg-dark h-200vh ng-tns-c82-0&quot;]/div[@class=&quot;d-flex flex-center flex-column flex-column-fluid ng-tns-c82-0&quot;]/div[@class=&quot;row rounded align-items-center flex-center mt-10 ng-tns-c82-0 ng-star-inserted&quot;]/div[@class=&quot;col-lg-6 w-lg-500px col-md-6 _login-card ng-tns-c82-0&quot;]/div[@class=&quot;card-bordered shadow card w-100 h-500px ng-tns-c82-0&quot;]/div[@class=&quot;w-100 mt-10 options-head ng-tns-c82-0&quot;]/div[@class=&quot;w-100 px-10 ng-tns-c82-0 ng-star-inserted&quot;]/form[@class=&quot;form w-100 mb-10 px-15 ng-tns-c82-0 ng-untouched ng-invalid ng-dirty&quot;]/div[@class=&quot;mb-3 ng-tns-c82-0&quot;]/div[@class=&quot;ng-tns-c82-0&quot;]/div[@class=&quot;fv-row mb-5 mt-5 ng-tns-c82-0&quot;]/input[@class=&quot;form-control text-center _h60 _ttu text-gray-700 fs-6 _fpoppins ng-tns-c82-0 ng-untouched ng-invalid ng-dirty&quot;]</value>
      <webElementGuid>7cc809f0-ea49-4c46-98b0-b75a8f852780</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @placeholder = 'Enter code here']</value>
      <webElementGuid>0744e9c0-037c-4f26-a756-c73b355f4c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='tel']</value>
      <webElementGuid>01dea2c6-a1e7-4a66-b080-05ec27362ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7601dc90-39cf-4344-97de-707bbb1ea8f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
