<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NSSF Number_form-control _h60 fs-7 ng_11b28d</name>
   <tag></tag>
   <elementGuidId>c8e418c5-2235-4c1c-8516-d56b7f39ec61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control._h60.fs-7.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;NSSF Number&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b0c30b2-137f-4b4c-9687-ff368393d89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>485c3448-e34a-41e3-9bec-ddd120f36584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>otherNssfReference</value>
      <webElementGuid>9ed2a49b-2e7e-49ed-a713-442da8822446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>NSSF Number</value>
      <webElementGuid>348959c7-e4d0-428b-b2bb-063aca94dc64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>8fcc360f-7ccb-4348-8003-686387d8cdfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>d5fa203d-f1a0-490f-bf5e-63c8f82853f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control _h60 fs-7 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>1dbe74b1-73b3-4163-b7c6-46ef4bd5022f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_drawer_example_dismiss&quot;)/div[@class=&quot;card rounded-0 w-100&quot;]/div[@class=&quot;card-body hover-scroll-overlay-y&quot;]/div[@class=&quot;card card-custom gutter-b _p50&quot;]/form[@class=&quot;form ng-dirty ng-touched ng-valid ng-submitted&quot;]/div[@class=&quot;row col-xl-12&quot;]/div[@class=&quot;col-sm-12 col-xl-5&quot;]/div[@class=&quot;form-group&quot;]/div[2]/div[@class=&quot;fv-row mb-7&quot;]/input[@class=&quot;form-control _h60 fs-7 ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>5825dff3-3d50-4924-9dba-58da9cefa197</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>4f538dd0-9114-406b-9ab8-638aafc5e7a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'NSSF Number']</value>
      <webElementGuid>4be5d15e-808f-4350-b254-db3931c6c83d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_drawer_example_dismiss']/div/div[2]/div/form/div/div/div/div[2]/div/input</value>
      <webElementGuid>216ea4cf-5a13-4a86-b4b7-e4349f781ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>7a183705-8243-4436-8b31-ef26eb77cfc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
