<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile Number or Email_form-control __9cb53f</name>
   <tag></tag>
   <elementGuidId>b414ebc3-2245-496b-b0e8-41492764a0ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @placeholder = 'Enter Mobile Number or Email here']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control._h60._ttu.text-gray-700.fs-7.fw-normal._fpoppins.text-center.email-mobile-field.ng-tns-c82-0.ng-untouched.ng-pristine.ng-invalid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Mobile Number or Email here&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>194fdbf3-556b-4726-838d-06c37a098446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>nssfnumber</value>
      <webElementGuid>80891094-207b-4419-ac0f-b7886287c7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>72659880-1d6a-499c-a2f6-c03d8451b66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>5e497962-a6b6-4be4-b749-aa10ba885e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Mobile Number or Email here</value>
      <webElementGuid>68f8a2b7-eaa9-4008-b668-191513c7a82f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e651e31e-2972-4cf9-b1ea-c37a97dc2e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control _h60 _ttu text-gray-700 fs-7 fw-normal _fpoppins text-center email-mobile-field ng-tns-c82-0 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>96a22e0f-5ed2-4782-91e8-6c8eb96140c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;header-fixed header-tablet-and-mobile-fixed aside-fixed aside-secondary-disabled&quot;]/app-root[1]/app-login[@class=&quot;ng-tns-c82-0 ng-star-inserted&quot;]/div[@class=&quot;d-flex flex-column flex-root ng-tns-c82-0&quot;]/div[@class=&quot;d-flex flex-column flex-lg-row flex-column-fluid stepper stepper-pills stepper-column ng-tns-c82-0&quot;]/div[@class=&quot;d-flex flex-column flex-lg-row-fluid py-10 bg-dark h-200vh ng-tns-c82-0&quot;]/div[@class=&quot;d-flex flex-center flex-column flex-column-fluid ng-tns-c82-0&quot;]/div[@class=&quot;row rounded align-items-center flex-center mt-10 ng-tns-c82-0 ng-star-inserted&quot;]/div[@class=&quot;col-lg-6 w-lg-500px col-md-6 _login-card ng-tns-c82-0&quot;]/div[@class=&quot;card-bordered shadow card w-100 h-500px ng-tns-c82-0&quot;]/div[@class=&quot;w-100 mt-10 options-head ng-tns-c82-0&quot;]/div[@class=&quot;w-100 px-10 ng-tns-c82-0 ng-star-inserted&quot;]/form[@class=&quot;form w-100 px-15 ng-tns-c82-0 ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;row ng-tns-c82-0&quot;]/div[@class=&quot;fv-row ng-tns-c82-0&quot;]/div[@class=&quot;position-relative mb-3 ng-tns-c82-0&quot;]/input[@class=&quot;form-control _h60 _ttu text-gray-700 fs-7 fw-normal _fpoppins text-center email-mobile-field ng-tns-c82-0 ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>af738471-c36c-42d7-bd19-e5a17e04614f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>347dd186-4235-4fa0-9c94-bcc6afb5c40a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>771037da-8b6f-40a1-9f19-d3cf61f6e00d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Enter Mobile Number or Email here']</value>
      <webElementGuid>6a98e7cb-844d-4769-9b04-cf3384ebc5bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
