<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sister_menuitems</name>
   <tag></tag>
   <elementGuidId>2a47f99e-16c8-4bca-8650-5892b339b9bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//span[text()='Relationship']//following::ng-dropdown-panel[@aria-label='Options list']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#aa0c1d3d15ee-4 > span.ng-option-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Sister&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9dfd473e-037e-4593-aeb3-5c44d7075cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option-label</value>
      <webElementGuid>c740e5b8-e642-4f65-8796-68eed0d0e4bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sister </value>
      <webElementGuid>a13a636f-2360-4f06-aee5-328d8c650fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aa0c1d3d15ee-4&quot;)/span[@class=&quot;ng-option-label&quot;]</value>
      <webElementGuid>5f2682cb-1da8-426e-8663-3c9f9dec53f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Sister ' or . = 'Sister ')]</value>
      <webElementGuid>de123fe2-9d26-4a29-89d3-4eabfc478a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brother'])[1]/following::span[1]</value>
      <webElementGuid>18cf46b5-de5f-49f9-b206-f3608a28e43c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardian'])[1]/following::span[2]</value>
      <webElementGuid>1357388d-a813-43c4-a432-fa3e26ae3a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Child'])[4]/preceding::span[1]</value>
      <webElementGuid>d147852e-17fc-471e-a879-8394e5c45a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Husband'])[1]/preceding::span[2]</value>
      <webElementGuid>f700d9bc-780c-4c4e-b9bf-d3a7a3b5aa3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sister']/parent::*</value>
      <webElementGuid>ae1118cb-a8ec-469f-b0a8-4c5f0c284db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aa0c1d3d15ee-4']/span</value>
      <webElementGuid>9627b4ad-56c5-4a9c-8295-f92f37c92a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/span</value>
      <webElementGuid>16b3a834-9bd9-416d-ad58-8724010f4897</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
