<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Contribution</name>
   <tag></tag>
   <elementGuidId>0a2d5bba-0d0f-41e6-88cb-5b77cbcc6182</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Contribution' or . = 'Contribution')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.form-check-sm:nth-child(1) ._fpoppins.form-check-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Contribution&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>db233d4d-5892-48a8-afa8-6b41e20df4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-label text-gray-600 fs-7 _fpoppins</value>
      <webElementGuid>f1155b5a-f446-49ff-84a0-5e8767bcbb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contribution</value>
      <webElementGuid>a95bac2d-55b9-4275-a259-ad21a863c136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Contribution</value>
      <webElementGuid>81ca1c79-0c9f-4621-83a6-7d22ca613781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c729600abf71364fad3693c347340867</value>
      <webElementGuid>1f40a2d2-5ae0-4ddc-b0de-874d8f91917e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check-sm ') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' _fpoppins ') and contains(concat(' ', normalize-space(@class), ' '), ' form-check-label ')]</value>
      <webElementGuid>07b260cf-631b-4197-82c6-19e5a2fc0b97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Contribution' or . = 'Contribution')]</value>
      <webElementGuid>b6898d9b-8aae-4d91-afa0-ad013f706cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check-sm ') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' _fpoppins ') and contains(concat(' ', normalize-space(@class), ' '), ' form-check-label ')]</value>
      <webElementGuid>2853d44b-1a69-4486-8fef-8e257d6f4147</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
