<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login</name>
   <tag></tag>
   <elementGuidId>747fbfba-fe12-4047-9108-9ad9e643e875</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Login' or . = 'Login')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.indicator-label.ng-tns-c82-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Login&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>297ebe27-3119-4022-8624-fd27cef14de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>indicator-label ng-tns-c82-0</value>
      <webElementGuid>75c0d7d4-9f4c-4f30-82cb-92841db1a1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>4dc935b0-f565-4c05-91a7-547b4a7c457a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;header-fixed header-tablet-and-mobile-fixed aside-fixed aside-secondary-disabled&quot;]/app-root[1]/app-login[@class=&quot;ng-tns-c82-0 ng-star-inserted&quot;]/div[@class=&quot;d-flex flex-column flex-root ng-tns-c82-0&quot;]/div[@class=&quot;d-flex flex-column flex-lg-row flex-column-fluid stepper stepper-pills stepper-column ng-tns-c82-0&quot;]/div[@class=&quot;d-flex flex-column flex-lg-row-fluid py-10 bg-dark h-200vh ng-tns-c82-0&quot;]/div[@class=&quot;d-flex flex-center flex-column flex-column-fluid ng-tns-c82-0&quot;]/div[@class=&quot;row rounded align-items-center flex-center mt-10 ng-tns-c82-0 ng-star-inserted&quot;]/div[@class=&quot;col-lg-6 w-lg-500px col-md-6 _login-card ng-tns-c82-0&quot;]/div[@class=&quot;card-bordered shadow card w-100 h-500px ng-tns-c82-0&quot;]/div[@class=&quot;w-100 mt-10 options-head ng-tns-c82-0&quot;]/div[@class=&quot;w-100 px-10 ng-tns-c82-0 ng-star-inserted&quot;]/form[@class=&quot;form w-100 px-15 ng-tns-c82-0 ng-dirty ng-valid ng-touched&quot;]/div[@class=&quot;text-center ng-tns-c82-0&quot;]/button[@class=&quot;btn btn-lg bg-nature fw-bolder w-100 _h60 fs-6 ng-tns-c82-0&quot;]/span[@class=&quot;indicator-label ng-tns-c82-0&quot;]</value>
      <webElementGuid>4d16b88e-da6f-439d-a1e3-35c2cbf815ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile Number or Email'])[1]/following::span[1]</value>
      <webElementGuid>b323a8e8-8356-4625-bceb-425a29fef521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One time passcode will be sent to the mobile number or Email provided'])[1]/following::span[1]</value>
      <webElementGuid>df2eb83e-1630-42fe-8e3e-a620165985f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Become a member'])[1]/preceding::span[2]</value>
      <webElementGuid>541aae87-f005-4b65-8e2d-c2d556bc086e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>0560b1fc-dbf8-4370-9ccb-b02959de415e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>9b015ffd-eb1f-474a-b714-6cfffbbdf7b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>76df65b4-9068-4c4c-acab-d06e9ae8b5bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
