<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Currency</name>
   <tag></tag>
   <elementGuidId>603a18a9-7c52-4e38-ae50-2cd85a68b52c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Currency' or . = 'Currency')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.col:nth-child(2) .fw-bold._fpoppins.text-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Currency&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>71fe2396-a90a-45f5-9e6b-124cca22ed4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fs-8 fw-bold text-gray-700 text-primary pb-1 px-2 _fpoppins</value>
      <webElementGuid>ec0a1d88-007a-4aaa-8c2b-2c62eb265a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Currency</value>
      <webElementGuid>8c9eb119-a7ce-44a1-8bf7-5e4958a90fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Currency</value>
      <webElementGuid>bae77412-1c4b-4795-9cbc-2970799dde37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-13b21406cf977d72dfd32b6a6935df6d</value>
      <webElementGuid>bc0e7636-5594-4a8d-ac08-d87d9b1fb23b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' col ') and (position() = 2)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' fw-bold ') and contains(concat(' ', normalize-space(@class), ' '), ' _fpoppins ') and contains(concat(' ', normalize-space(@class), ' '), ' text-primary ')]</value>
      <webElementGuid>35b8e268-1eb1-4fc2-b122-f6aceb84dc5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Currency' or . = 'Currency')]</value>
      <webElementGuid>037d44ae-bada-412a-807a-5828b7dfeff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' col ') and (position() = 2)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' fw-bold ') and contains(concat(' ', normalize-space(@class), ' '), ' _fpoppins ') and contains(concat(' ', normalize-space(@class), ' '), ' text-primary ')]</value>
      <webElementGuid>9af40ddc-55dc-46a3-9c95-cbb42e07203e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
