<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_contributions_menu-icon</name>
   <tag></tag>
   <elementGuidId>e9aec9ac-44fe-409f-8243-9a8a525dbf43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//*[@aria-label='Contributions']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;kt_aside_menu_wrapper&quot;)/div[@id=&quot;kt_aside_menu&quot;]/div[@class=&quot;menu-item py-3&quot;]/a[@class=&quot;menu-link active&quot;]/span[@class=&quot;menu-icon&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Contributions&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b0d81215-79bb-424e-8f9b-58583a8bf0c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-icon</value>
      <webElementGuid>b0e12c5d-4876-4957-a287-327bc60bf853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_aside_menu_wrapper&quot;)/div[@id=&quot;kt_aside_menu&quot;]/div[@class=&quot;menu-item py-3&quot;]/a[@class=&quot;menu-link active&quot;]/span[@class=&quot;menu-icon&quot;]</value>
      <webElementGuid>abd269cb-0e2d-4787-aa4e-1ed94becb2a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dasboard'])[1]/following::span[1]</value>
      <webElementGuid>735483c9-fa95-4001-b4c3-6ed038e7d03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-statement'])[1]/preceding::span[2]</value>
      <webElementGuid>55cde33b-9b32-41b4-8818-fa5e954107dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Profile'])[1]/preceding::span[6]</value>
      <webElementGuid>6be877c5-7336-4d3a-8553-5474ff73ed5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_aside_menu']/div[2]/a/span</value>
      <webElementGuid>952d02c2-e9e5-4dab-8bc4-ca63b4f87b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/span</value>
      <webElementGuid>e7550348-4a5e-4398-9490-945424636ed7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
