<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_menu-icon</name>
   <tag></tag>
   <elementGuidId>4164a848-9bfa-484e-aaa4-24cef8ae1493</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'menu-icon' or . = 'menu-icon')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;Estatement&quot;] .menu-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Estatement&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0ca2cd3a-b783-42c2-9e73-95fcd3cb0265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-icon</value>
      <webElementGuid>f14a5e1b-7e42-4ba6-b2a7-2995a7761089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>menu-icon</value>
      <webElementGuid>f38b7849-cfa4-4f2f-b0f1-5b1b3154ac3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-61786e7a2c6de6a42fabfc26504e8e2a</value>
      <webElementGuid>351f0e4c-e71a-4376-a201-9b5095d04ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Estatement']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' menu-icon ')]</value>
      <webElementGuid>d3065240-bcab-4320-b7cf-636a53000b75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'menu-icon' or . = 'menu-icon')]</value>
      <webElementGuid>6d1948cc-2c28-43a5-becf-9a2e7fcdfb57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Estatement']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' menu-icon ')]</value>
      <webElementGuid>2c09f972-558b-4cc4-92f0-0c0b947651af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
