<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_256776712231</name>
   <tag></tag>
   <elementGuidId>2d5c0490-1134-44dc-8167-b38d62613e97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(name() = 'tr') and (position() = 3)]//td[@class and contains(concat(' ', normalize-space(@class), ' '), ' fw-boldest ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-child(3) td.fw-boldest</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;256776712231&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>bd82e795-c771-49cb-bf43-be6c55ffb838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-boldest</value>
      <webElementGuid>33ff1610-6abe-4a8d-adce-e6a13c2bad87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>256776712231</value>
      <webElementGuid>ae060b9f-cd0e-4df4-a53a-f5f4904319e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>256776712231</value>
      <webElementGuid>637969d5-c04f-41e3-8992-58162a4401a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-52eaabbe341e77d4c5e10e0226c15361</value>
      <webElementGuid>0fce4fc3-f22b-4750-a215-4954f0f9c25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(name() = 'tr') and (position() = 3)]//td[@class and contains(concat(' ', normalize-space(@class), ' '), ' fw-boldest ')]</value>
      <webElementGuid>52d4e972-e2dd-44cc-8bcc-544e6e267b83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '256776712231' or . = '256776712231')]</value>
      <webElementGuid>64c45571-1397-461d-9a35-f1b3a67b4d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(name() = 'tr') and (position() = 3)]//td[@class and contains(concat(' ', normalize-space(@class), ' '), ' fw-boldest ')]</value>
      <webElementGuid>cc5ce838-0ce8-49c0-b674-fcf613b8ff31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
