<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_katsmakaatogmail.com</name>
   <tag></tag>
   <elementGuidId>beb76d89-aa57-4dbc-ba4e-8281618a6b2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(name() = 'tr') and (position() = 4)]//td[@class and contains(concat(' ', normalize-space(@class), ' '), ' fw-boldest ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-child(4) td.fw-boldest</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;katsmakaato@gmail.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a63abea2-2811-444c-93d9-7a502cce9bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-boldest</value>
      <webElementGuid>47c971d0-6a84-4bfa-965e-b89a52808856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>katsmakaato@gmail.com</value>
      <webElementGuid>14457666-cb41-479b-8356-4f1a9d03c79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>katsmakaato@gmail.com</value>
      <webElementGuid>7fc64f21-3655-49a5-be01-f94ded744936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3f86e4bd1d32de3cca25415387b345fc</value>
      <webElementGuid>52f872e9-d540-417d-9279-5b0973a28923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(name() = 'tr') and (position() = 4)]//td[@class and contains(concat(' ', normalize-space(@class), ' '), ' fw-boldest ')]</value>
      <webElementGuid>84cd6c2d-22cc-4501-8bde-41f2f4eabed9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'katsmakaato@gmail.com' or . = 'katsmakaato@gmail.com')]</value>
      <webElementGuid>d64a787b-53c9-4b3f-8905-c4464fa06926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(name() = 'tr') and (position() = 4)]//td[@class and contains(concat(' ', normalize-space(@class), ' '), ' fw-boldest ')]</value>
      <webElementGuid>397330cc-0aac-43d8-ad5e-afcdaa69ab05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
