<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Employer</name>
   <tag></tag>
   <elementGuidId>3da051b3-84b9-4495-8e20-44f1fa5d8c00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.min-w-100px</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[(text() = 'Employer' or . = 'Employer')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Employer&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>dccbd01f-bd68-421d-95bb-137e0ed692b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>min-w-100px</value>
      <webElementGuid>df971cb0-afac-4b96-9ae1-bc212a8c82dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employer</value>
      <webElementGuid>b980c536-2dcd-4499-a101-ddcfb73a4935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_customer_view_overview_tab&quot;)/div[@class=&quot;card shadow mb-6 mb-xl-9&quot;]/div[@class=&quot;card-body pt-0 pb-5&quot;]/table[@class=&quot;table align-middle table-row-dashed table-bordered gy-5&quot;]/thead[@class=&quot;border-bottom border-gray-300 fs-7 fw-bolder&quot;]/tr[@class=&quot;text-start text-muted text-gray-800 gs-0 py-5&quot;]/th[@class=&quot;min-w-100px&quot;]</value>
      <webElementGuid>05aba2a0-bb62-4a11-8159-8f75a83dcf97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Employer' or . = 'Employer')]</value>
      <webElementGuid>3f514152-c024-48a0-adce-2f81fcc92fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employment History'])[2]/following::th[1]</value>
      <webElementGuid>0b4c3497-14ce-473f-bfad-561590d218ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/following::th[1]</value>
      <webElementGuid>73305c04-2dca-4f16-84a8-2b14ff008dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount (Ugx)'])[1]/preceding::th[1]</value>
      <webElementGuid>87ecffda-fb71-4ad7-855d-b3e6cef2443a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Timeline'])[1]/preceding::th[2]</value>
      <webElementGuid>45693be5-8b7f-41b8-a623-aeadf5cb302c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Employer']/parent::*</value>
      <webElementGuid>2947cfa6-c627-4aa9-b1a5-2849461cdd3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_customer_view_overview_tab']/div/div[2]/table/thead/tr/th</value>
      <webElementGuid>f000392c-734d-49a2-907f-410c826dac96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th</value>
      <webElementGuid>7fceeb17-6bb9-483b-80dd-10a73dd7cc44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
